import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const VAULT_PLUGIN_DIR =
	'/Users/amanda/Library/Mobile Documents/iCloud~md~obsidian/Documents/PKM/.obsidian/plugins/tasks-companion-pane';

const copyToVault = () => {
	try {
		mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
		copyFileSync('main.js', `${VAULT_PLUGIN_DIR}/main.js`);
		copyFileSync('styles.css', `${VAULT_PLUGIN_DIR}/styles.css`);
		copyFileSync('manifest.json', `${VAULT_PLUGIN_DIR}/manifest.json`);
		console.log('[deploy] Copied to vault plugin folder.');
	} catch (e) {
		console.warn('[deploy] Could not copy to vault:', e.message);
	}
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		{
			name: 'deploy',
			setup(build) {
				build.onEnd(() => copyToVault());
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
